camera0: 4
camera1: 6
frame_width: 1280
frame_height: 720
mono_calibration_frames: 7
stereo_calibration_frames: 7
view_resize: 1
checkerboard_box_size_scale : 1
checkerboard_rows: 6
checkerboard_columns: 8
cooldown: 100
